FROM eclipse-temurin:21-jre-alpine
LABEL maintainer="kimdoyun0806 gim_doyun@naver.com"
LABEL version="1.0"

# jar 복사 (상대경로 기준은 Dockerfile 위치 기준, build/libs 경로 유지)
COPY build/libs/hanbando-be-0.0.1-SNAPSHOT.jar /root/app.jar

WORKDIR /root
EXPOSE 8080
CMD ["java", "-jar", "app.jar"]
