#name: CI/CD with Helm on NKS (Docker Hub)
#
#on:
#  push:
#    branches: [ "main" ]
#
#jobs:
#  build-and-deploy:
#    runs-on: ubuntu-latest
#
#    steps:
#      # 1. Checkout
#      - name: Checkout
#        uses: actions/checkout@v3
#
#      # 2. JDK & Build JAR
#      - name: Set up JDK 21
#        uses: actions/setup-java@v3
#        with:
#          distribution: temurin
#          java-version: 21
#
#      - name: Build JAR
#        run: ./gradlew clean build -x test
#
#      # 3. Docker build & Push (Docker Hub)
#      - name: Set up Docker
#        uses: docker/setup-buildx-action@v2
#
#      - name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKERHUB_HJ_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_HJ_PASSWORD }}
#
#      - name: Build and push Docker image
#        run: |
#          IMAGE=docker.io/${{ secrets.DOCKERHUB_HJ_USERNAME }}/hanbando-app:${{ github.sha }}
#          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
#          docker build -t $IMAGE .
#          docker push $IMAGE
#
#      # 4. Set up kubectl & Helm
#      - name: Set up kubectl
#        uses: azure/setup-kubectl@v3
#        with:
#          version: 'latest'
#
#      - name: Set up Helm
#        uses: azure/setup-helm@v3
#        with:
#          version: 'latest'
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Configure kubeconfig
#        run: |
#          mkdir -p ~/.kube
#          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > ~/.kube/config
#
#      - name: Verify K8s Connection
#        run: kubectl get nodes
#
#      # 5. Deploy using Helm
#      - name: Helm upgrade
#        run: |
#          helm upgrade --install hanbando-app ./helm \
#            --namespace default \
#            --create-namespace \
#            --set image.repository=docker.io/${{ secrets.DOCKERHUB_HJ_USERNAME }}/hanbando-app \
#            --set image.tag=${{ github.sha }} \
#            --set secrets.DB_HOST="${{ secrets.DB_HOST }}" \
#            --set secrets.DB_PORT="${{ secrets.DB_PORT }}" \
#            --set secrets.DB_NAME="${{ secrets.DB_NAME }}" \
#            --set secrets.DB_USERNAME="${{ secrets.DB_USERNAME }}" \
#            --set secrets.DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
#            --set secrets.REDIS_HOST="${{ secrets.REDIS_HOST }}" \
#            --set secrets.REDIS_PORT="${{ secrets.REDIS_PORT }}" \
#            --set secrets.JWT_SECRET="${{ secrets.JWT_SECRET }}" \
#            --set secrets.SMTP_HOST="${{ secrets.SMTP_HOST }}" \
#            --set secrets.SMTP_PORT="${{ secrets.SMTP_PORT }}" \
#            --set secrets.SMTP_USERNAME="${{ secrets.SMTP_USERNAME }}" \
#            --set secrets.SMTP_PASSWORD="${{ secrets.SMTP_PASSWORD }}"
#        shell: bash
#
#
#      - name: Verify rollout
#        run: kubectl rollout status deployment/hanbando-app